name: cicd
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
#
#      - name: run code quality checks
#        run:
#
#      - name: run tests
#        run:

      - name: build with gradle
        run: ./gradlew clean bootJar

      - name: upload artifact
        uses: actions/upload-artifact@v2
          path: build/libs/bigly-producer*.jar

#      - name: build docker image
#        run: ./gradlew clean bootBuildImage
#
#      - name: upload docker image
#        run:
#
#      - name: deploy docker image